const MARKET_ARBITRAGE_THRESHOLD = process.env.MARKET_ARBITRAGE_THRESHOLD || 10.0;
const COIN_GECKO_TOKEN_ID = process.env.COIN_GECKO_TOKEN_ID || 'cheqd-network';

exports.MARKET_ARBITRAGE_THRESHOLD = MARKET_ARBITRAGE_THRESHOLD;
exports.COIN_GECKO_TOKEN_ID = COIN_GECKO_TOKEN_ID;
