const MARKET_ARBITRAGE_THRESHOLD =
  process.env.MARKET_ARBITRAGE_THRESHOLD || 10.0;
const COINGECKO_TOKEN_ID = process.env.COINGECKO_TOKEN_ID || 'cheqd-network';

exports.MARKET_ARBITRAGE_THRESHOLD = MARKET_ARBITRAGE_THRESHOLD;
exports.COINGECKO_TOKEN_ID = COINGECKO_TOKEN_ID;
