name: "Build"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  build-docker:
    name: "Build Docker image"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: registry.digitalocean.com/${{ github.repository }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
          version: latest
      
      - name: Configure Docker image metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=staging-latest
            type=sha,format=long

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          load: true
          target: runner
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=min
      
      - name: Save Docker image
        run:  docker save ${{ env.IMAGE_NAME }} > market-monitoring-staging.tar

      - name: Upload build image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: market-monitoring-staging
          path: market-monitoring-staging.tar
  
  cache-purge:
    name: "Purge branch Actions cache"
    needs: build-docker
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    
    steps:

      - name: "Delete Branch Cache Action"
        uses: snnaplab/delete-branch-cache-action@v1.0.0
        with:
          # Specify explicitly because the ref at the time of merging will be a branch name such as 'main', 'develop'
          ref: refs/pull/${{ github.event.number }}/merge
          github-token: ${{ secrets.GITHUB_TOKEN }}
